### ISSUE TITLE
Clone to an organization repository?

### ISSUE THREAD

**Issue by tonysneed** [gatewayapps/kamino#103]
I would like to clone issues from one repository to another within the same organization, but I don't see the org repositories in the drop down.  Is this possible?

**Comment by johnmurphy01** [comment]
@tonysneed as long as you are a member of the repository, you should see it in the list of repositories to clone to. If you can confirm you are a member of the repository and you still do not see the repo in the list, please let me know. Also let me know about how many repos you have in your list. 

I retrieve the list using the Github API, making the following request. The description below will give you more info about the repos you should be able to see:
`GET /users/repos`
```
List repositories that are accessible to the authenticated user.

This includes repositories owned by the authenticated user, repositories where the authenticated user is a collaborator, and repositories that the authenticated user has access to through an organization membership.
```

**Comment by tonysneed** [comment]
Thanks - all good now.

**Comment by johnmurphy01** [comment]
Good to hear!
