### ISSUE TITLE
Doesn't Clone to someone else's repo

### ISSUE THREAD

**Issue by demisjohn** [gatewayapps/kamino#108]
In my dropdown list, the extension works as expect if I choose one of my own repos.  However, I actually want to clone to another user's repo, of which I am a collaborator.

When I select the other user's repo, the issues page jumps/scrolls to the top and no popup window appears (which would have asked "clone and close?" etc.).  But it works exactly as expected for my own repos.
I have collaborator access to the other repo, and can create issues, since it's a public repo.

Mac OS 10.12.6, Chrome Version 65.0.3325.181 (Official Build) (64-bit)

<img width="278" alt="screen shot 2018-04-10 at 9 16 08 pm" src="https://user-images.githubusercontent.com/5370181/38596177-ee78abf8-3d04-11e8-8ad7-56b4d7588981.png">

**Comment by johnmurphy01** [comment]
@demisjohn thanks for the feedback! This sounds like a permission issue. I'll investigate.

**Comment by johnmurphy01** [comment]
Closing due to lack of response from the OP. If this is still an issue, feel free to re-open and provide more detailed information

**Comment by demisjohn** [comment]
Hello Mr. Murphy,
Sorry I probably won't be able to try this again and give you more error
info about it.

--                             Demis                             --
°•Oo.oO•°*°•Oo. Sound  OK
<http://www.google.com/search?q=sound+ok+horn&tbm=isch>  Horn *°•Oo.oO•°*°•O
o.
