### ISSUE TITLE
Manually entering Owner/Repo

### ISSUE THREAD

**Issue by CamSoper** [gatewayapps/kamino#109]
I work for Microsoft. I'm in five or six orgs, which provides me access to literally hundreds (thousands?) of repos. Finding the repo I need in the list is a chore, and, for some reason, they don't all show up, even when they should.

I'd love the option to just type the owner/repo I want to transfer the issue to and then display an exception if it turns out I don't have the rights.

**Comment by johnmurphy01** [comment]
@CamSoper thanks for the feedback! A search filter sounds like a great idea. Also, a little bit concerning, is why all of your repositories aren't showing up in the dropdown list. I'll see what I can do about a search filter and, along the way, investigate what's up with populating the repo list.

**Comment by CamSoper** [comment]
I'm not much of a frontend developer, but if you need me to debug/dump anything on the missing repos situation, let me know.  I can repro reliably.

**Comment by johnmurphy01** [comment]
Absolutely, that would help. If there's anything in the dev console or anything of significance in the network requests, that may help shed some light on the issue. I am not fortunate enough to have access to many hundred repos :)

**Comment by CamSoper** [comment]
So I ran it with the dev tools open and tracked the network performance.  You know how you pull down the repo list paginated in groups of 100?  Turns out I have 48 (!!!) pages of repos to pull down.  Dropping a repo here or there *could* be on your end, but I'm betting it's on the GitHub side.  I didn't go digging through 48 JSON responses to find out, though.  😆 

Closing and reopening the browser is apparently enough to reset the cache and make it pull them down again, though.  I don't know if I got the complete list as I have no intention of auditing all 4800+ repos, but the ones I had been missing showed up.

**Comment by johnmurphy01** [comment]
Oh wow! That's a lot of repos! Yeah, definitely a use case for a search filter

**Comment by johnmurphy01** [comment]
@CamSoper I've just published version `2.9.1` to the Chrome Web Store. Look for it to be available soon. If you don't mind, please update when you can and see if the experience is better for you with the search filter and hopefully I've fixed your repo loading issues as well.

**Comment by CamSoper** [comment]
Just updated!  Much better experience!  Thank you, friend!

**Comment by johnmurphy01** [comment]
Excellent! Thank you for the suggestion. I will close this issue

**Comment by johnmurphy01** [comment]
@all-contributors please add @CamSoper for bug and ideas
