### ISSUE TITLE
Add link to new issue in "Kamino closed and cloned.." comment

### ISSUE THREAD

**Issue by rbetts** [gatewayapps/kamino#111]
Would you accept a PR to add a link to the new issue in the comment that Kamino adds to the old repo? It would be nice to cross-link the issues.

https://github.com/gatewayapps/kamino/blob/master/app.js#L327

**Comment by johnmurphy01** [comment]
Sure, feel free to create a PR and I will review, otherwise I'll treat it as a backlog item for myself. Not sure why I didn't go ahead and make the cross link in the first place...

**Comment by adamperlin** [comment]
Thought this would be useful, so I just opened a PR which addresses this: #112

**Comment by johnmurphy01** [comment]
Thanks! I'll do a full review/test soon but as I said in the PR, looks good at a high level

**Comment by johnmurphy01** [comment]
I've merged #112. I will try to get a new version in the Google Chrome store today or tomorrow

**Comment by adamperlin** [comment]
Awesome thanks so much!

**Comment by johnmurphy01** [comment]
Omg, so sorry guys. I forgot to roll out a new version of the extension. I'll do that right now. Life has been busy lately :)

**Comment by johnmurphy01** [comment]
In version `2.9.2`. Again sorry for the delay all

**Comment by johnmurphy01** [comment]
@all-contributors please add @adamperlin for code and @rbetts for ideas

**Comment by johnmurphy01** [comment]
@all-contributors please add @rbetts for ideas
