### ISSUE TITLE
Allow to enter any public repo

### ISSUE THREAD

**Issue by aeschli** [gatewayapps/kamino#116]
I need to move issue to other public repos which I'm not a member of. Is that possible?

When entering the name to the search box, no entry shows up and there's no way to invoke the move

**Comment by johnmurphy01** [comment]
That is not possible with Kamino. You have to be a member of the repository to which you are attempting to clone. If anyone could clone to any public repo, you can imagine what could happen if someone wanted to be malicious.

You'll need to get permission from the repo owner and become a member first.
