### ISSUE TITLE
Post returns 410 (Gone) when issues are turned off for destination repository

### ISSUE THREAD

**Issue by pavog** [gatewayapps/kamino#122]
Hi, when I try to use this extension the following error is getting printed to my browser console:

`https://api.github.com/repos/pavog/myrepo/issues 410 (Gone)`

The github developer api describes the endpoint over [here](https://developer.github.com/v3/issues/#create-an-issue).

**Comment by johnmurphy01** [comment]
Hi @pavog. That is coming directly from the Github api. 

Can you provide more detail about what operation you are trying to perform? For example, are you trying  to actually clone an issue or is this happening before then?

**Comment by pavog** [comment]
Hi, I found out that this is problem occurs only if issues are not enabled on my reporitory, which is the default for forked repositories, unfortunately.

Maybe you can add a check for this (if the issues are enabled in the repo settings) and display a proper waring / error message.

**Comment by johnmurphy01** [comment]
Good find! I can probably do that but ideally if you're trying to clone to a repo that has issue creation disabled, it would be smarter of Kamino to enable issue creation via an API call. I'll put this in the backlog to  either:
- present a warning message letting the user know that the repo they are cloning to doesn't allow issue creation
- automatically enable issue creation if disabled

**Comment by pavog** [comment]
Sounds good. Thanks!

**Comment by johnmurphy01** [comment]
Looks like you can `PATCH` the repository and enable issues by setting `has_issues` to `true`:
https://developer.github.com/v3/repos/#edit

If using Kamino, then I will make the assumption that issues need to be enabled for the repo. I will call the above endpoint and then cloning should be possible after the fact.

**Comment by johnmurphy01** [comment]
@all-contributors please add @pavog for bug
