### ISSUE TITLE
Cloned comments should contain original poster and link

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/kamino#139]
Cloned comments should contain the original poster(as a link) and a link back to the original comment

**Comment by ctopinka** [comment]
Also, I'm only seeing my own comments in the clone.

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/10)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/11)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/12)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/13)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/24)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/25)

**Comment by johnmurphy01** [comment]
I believe this issue was resolved with #213
