### ISSUE TITLE
Kamino-backdrop fade blocks buttons

### ISSUE THREAD

**Issue by SteffanoP** [gatewayapps/kamino#144]
So I was using this tool for the first time, and when i gave a try, a problem happened that there is a fade blocking the buttons of being pressed, as you can see in the printscreen below. 

![SharedScreenshot](https://user-images.githubusercontent.com/26782009/61987923-3d2f4d00-aff1-11e9-8f01-b6da1d2dfc84.jpg)

So I used an adblock to block the following div: `<div class="kamino-backdrop fade in"></div>` and it worked.

**Comment by Expedition13Admin** [comment]
Confirmed

**Comment by zhaong** [comment]
**Workaround:**
Use Adblock to block the following div: `<div class="kamino-backdrop fade in"></div>`
Add block rule `##div[class="kamino-backdrop fade in"]`

**Comment by Ornias1993** [comment]
Thats a workarround, but it would be nice if people like: Fix their bugs. 
I know its like talking unicorns, but still.

**Comment by johnmurphy01** [comment]
@SteffanoP thanks for the bug report! I'll check this out as soon as I can and see if I can provide a fix that doesn't involve a workaround.

@Ornias1993 awesome joke! 

But seriously, this is an open source project. Anyone who has the inclination can provide a PR and I will review it and include it in the project if it passes review. I work on Kamino in my free time, unfortunately free time has been limited lately.

**Comment by johnmurphy01** [comment]
@SteffanoP @zhaong @Expedition13Admin @Ornias1993 I have just released version `2.10.1` of Kamino to the Chrome store. Once you've received the latest version, please give it a try. I will close this issue once I receive word that the bug is fixed

**Comment by johnmurphy01** [comment]
@all-contributors please add @SteffanoP for bug

**Comment by Ornias1993** [comment]
@johnmurphy01 Wasn't meant to be a jackass.
I think we all know the time struggles and need to pick our opensource fights to fight. 
I'll update, check it out and respond back in a sec!

**Comment by Ornias1993** [comment]
Checked, works fine! Thanks! :)

**Comment by johnmurphy01** [comment]
@Ornias1993 no worries. Thanks for verifying!
