### ISSUE TITLE
Disable comment on clone

### ISSUE THREAD

**Issue by Ornias1993** [gatewayapps/kamino#145]
It would be nice if we could clone an issue, without commenting.
I dont like spamming the upstream of a project because I copy some issues.

**Comment by johnmurphy01** [comment]
Understandable. I can add an option in the settings page to turn off automatic comments. By default, the extension would work as it does now. If you toggle, then cloning will only clone the issue and any comments rather than injecting the Kamino related comments

**Comment by johnmurphy01** [comment]
@all-contributors please add @Ornias1993 for ideas

**Comment by JamesNewton** [comment]
How much would it cost to make this happen like right now? I really need it.

**Comment by johnmurphy01** [comment]
@JamesNewton nothing at all, but thanks for the donation anyway! I can work on it right now

**Comment by johnmurphy01** [comment]
@JamesNewton I have implemented the feature. The soonest I can deploy the new version would be tomorrow morning, does that work for you? I don't currently have access to my key file in order to package the extension up
