### ISSUE TITLE
Difficult to click Kamino button

### ISSUE THREAD

**Issue by johnmurphy01** [gatewayapps/kamino#152]
The Kamino button is difficult to click. I believe the content below the button is obstructing the button and there should be some padding/margin to separate the content.

**Comment by radiantly** [comment]
Hi, can I work on this?

**Comment by johnmurphy01** [comment]
Absolutely! If you're doing it for Hacktoberfest, just make sure to wait and make your PR after October 1

**Comment by johnmurphy01** [comment]
I have created a release(`v2.10.2`) that is pending review by Google. They have updated their review policies for extensions so it could take longer than normal to appear in the store
