### ISSUE TITLE
Allow Enterprise Githubs

### ISSUE THREAD

**Issue by sjsaha** [gatewayapps/kamino#153]
Please provide option to fully access custom URL - for enterprise githubs in a private network

**Comment by sjsaha** [comment]
![Untitled](https://user-images.githubusercontent.com/7125423/71049208-ac623500-217c-11ea-9f87-e9841b36e6ab.png)

**Comment by johnmurphy01** [comment]
Thanks for the feedback! I will have to investigate to see if this is possible.

**Comment by frekel** [comment]
I would like this too!!

**Comment by johnmurphy01** [comment]
@all-contributors please add @sjsaha for ideas

**Comment by johnmurphy01** [comment]
@sjsaha I have an in progress branch where I am attempting to make this work.

If possible, could you pull down this branch: https://github.com/gatewayapps/kamino/tree/enhancement/153-allow-enterprise

and load the unpacked extension into Chrome and then check to see if Kamino works for you in your Github Enterprise instance? I don't have access to an Enterprise instance, so it's hard to say if this is working or not.

Here are the basic instructions if you weren't aware: https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

**Comment by sjsaha** [comment]
Hi All,

Sorry for the late reply. I have moved to a new organization where I don't
have access to Github Enterprise.

**Comment by johnmurphy01** [comment]
@sjsaha no worries, hope your move went well!

**Comment by johnmurphy01** [comment]
To anyone who has an Enterprise account, I have posted instructions above if you would like to help test Kamino for Enterprise Github. Just post here with the results

**Comment by natasab** [comment]
For me it worked in SAP Enterprise account and i followed the instructions, thank you for this extension.
* Is it possible to exclude "Kamino cloned this issue to XYZ" from the comment of the source issue?
* is it possible to select multiple issue and clone them at once?

**Comment by johnmurphy01** [comment]
@natasab thank you for verifying! 

Regarding your other questions:
- There is another issue related to suppressing the clone message on the original issue
- Currently no it's not possible to bulk clone issues. With the way Kamino is written, it's more for single issue cloning. However I don't think it would be impossible to extend Kamino to do this
- Currently you cannot remove the mention from the issue but that could be an enhancement for Kamino for certain

**Comment by natasab** [comment]
@johnmurphy01  thank you!

> Regarding your other questions:
> * There is another issue related to suppressing the clone message on the original issue
> * Currently you cannot remove the mention from the issue but that could be an enhancement for Kamino for certain

I found my way how to make this work by applying the changes to the code locally as a quick and dirty workaround :)

**Comment by johnmurphy01** [comment]
@natasab  Great! If you want to contribute to this repo, feel free to make a PR

**Comment by johnmurphy01** [comment]
Without being able to test, based on other feedback I am under the impression that github enterprise and kamino are working well together. Closing this
