### ISSUE TITLE
Show full repo name in a tool-tip on hover (name currently gets truncated in the drop-down view)

### ISSUE THREAD

**Issue by jmah-cc** [gatewayapps/kamino#155]
Currently some of the repos I'm using have long names and if they belong to the same org, it's hard to distinguish which repo is which. It'd be great if you show a tool-tip on hover so we can easily see the full repo name:

![image](https://user-images.githubusercontent.com/57732952/87704919-f2eb3280-c751-11ea-9952-62a8c729493e.png)

**Comment by johnmurphy01** [comment]
@all-contributors please add @jmah-cc for ideas

**Comment by johnmurphy01** [comment]
@all-contributors please add @jmah-cc for ideas

**Comment by nowakprojects** [comment]
Kamino cloned this issue to [CodersCamp2020/auto-grading-test-nowakprojects](https://github.com/CodersCamp2020/auto-grading-test-nowakprojects/issues/2)

**Comment by johnmurphy01** [comment]
This issue is resolved and will be in the newest version of the extension soon. Thanks @NathanWaddell121107 !
