### ISSUE TITLE
Support new GitHub dark mode

### ISSUE THREAD

**Issue by fharper** [gatewayapps/kamino#165]
It's really difficult to read the repository list when you use the new GitHub dark mode
![image](https://user-images.githubusercontent.com/1170989/103799778-8a528380-5019-11eb-96cf-96291fb3cba5.png)

**Comment by johnmurphy01** [comment]
@fharper indeed it is! I had noticed this but haven't had a chance to put in the work to fix. I'll try to get to it as soon as I can

**Comment by johnmurphy01** [comment]
@all-contributors please add @fharper for bugs

**Comment by johnmurphy01** [comment]
@all-contributors please add @maciejwalkowiak for code
