### ISSUE TITLE
[BUG] Cloned issues have their comments "scrambled" 

### ISSUE THREAD

**Issue by julianzz98** [gatewayapps/kamino#180]
**Describe the bug**
When cloning a GitHub issue to another repository, the comments of the original issue are *sometimes* scrambled in the cloned ticket.

**To Reproduce**
1. Go to your repository, choose a issue with maybe some more comments (e.g. 10)
2. Click on clone to "your repository"
3. Check how the comments are sorted in the cloned ticket

**Expected behavior**
The comments are supposed to be in the right order.

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version 95.0.4638.69 (64-Bit)

**Additional context**
I am still unsure if there are any clues, but maybe it has to do with the size of the comment. But this would suggest in the first place, that smaller comments are copied first. In this case it seems more like that bigger comments are copied first, smaller ones later.

**Comment by johnmurphy01** [comment]
Thanks for the report! My guess is that maybe the comments do not come in from the GitHub api in the right order. Possibly we will have to sort them ourselves or figure out the right parameter to pass to the api to sort them.

**Comment by thomas694** [comment]
The GitHub API is working correctly. The order is randomly, mainly depending on network latency, because the promises are executed concurrently already at their time of creation.
I created a PR to fix it.
