### ISSUE TITLE
[BUG]  Comments lose owner

### ISSUE THREAD

**Issue by liquidcms** [gatewayapps/kamino#200]
**Describe the bug**
When an issue is cloned with the comments; all the comments end up showing as authored by me.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by johnmurphy01** [comment]
@all-contributors please add @liquidcms for bugs

**Comment by johnmurphy01** [comment]
I haven't been able to replicate this with the most recent changes to Kamino. Please check if this is still occurring for you. If so, open another bug issue and I will try to replicate
