### ISSUE TITLE
[BUG] Extension's styles break layout for "Checks..." section on pull requests

### ISSUE THREAD

**Issue by patrickhlauke** [gatewayapps/kamino#202]
**Describe the bug**

When the extension is installed/enabled, items in the "Checks..." section on pull requests break out of their container box.

<img width="929" alt="Screenshot showing a failing 'Check', with its item overflowing the overall 'Checks' container left and right" src="https://github.com/gatewayapps/kamino/assets/895831/e1963661-1b00-4b58-b69b-16d6994ad8b2">

Disabling the extension and reloading, the problem goes away, so it's definitely related to whatever styles this extension injects.

<img width="925" alt="Screenshot of the same section, now with the correct layout" src="https://github.com/gatewayapps/kamino/assets/895831/8c5b9535-a78a-43f8-b770-2d8053b8cd06">

PR used to test this: https://github.com/w3c/wcag/pull/3909 (though it'll likely be merged and closed by the time this gets looked at)

**To Reproduce**
1. Go to a pull request with checks with the extension enabled - observe the problem with layout
2. Disable the extension
3. Reload the page - notice the layout problem is gone

**Expected behavior**

The styles should not break the layout of the "Checks..." section.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows and macOS
 - Browser: Chrome
 - Version: Latest

**Comment by johnmurphy01** [comment]
@all-contributors please add @patrickhlauke for bugs

**Comment by johnmurphy01** [comment]
@patrickhlauke thanks! I verified you bug report. It looks like I'm indeed using a `open` class and setting the display to inline. GitHub also uses a `open` class but they aren't putting any CSS styling into it. So I should be able to scope my CSS so that it doesn't affect other parts of the page.

**Comment by patrickhlauke** [comment]
lovely, thank you

**Comment by johnmurphy01** [comment]
@patrickhlauke I've submitted a new version of Kamino (4.0.1). Once it's approved by the web store, it should be available.

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/14)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/15)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/16)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/17)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/18)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/19)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/20)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/21)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/22)

**Comment by johnmurphy01** [comment]
Kamino cloned this issue to [johnmurphy01/aac-speech-app](https://github.com/johnmurphy01/aac-speech-app/issues/23)
