### ISSUE TITLE
[BUG] Latest version throws errors/doesn't work

### ISSUE THREAD

**Issue by patrickhlauke** [gatewayapps/kamino#214]
**Describe the bug**
Not sure if this is a new change in latest version, or some change in Chrome, but the extension stopped working today.

Looking at the extension errors, it complains about

```
Refused to load the script 'https://code.jquery.com/jquery-3.6.0.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Refused to load the script 'https://code.jquery.com/jquery-3.6.0.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Refused to load the script 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Refused to load the script 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**To Reproduce**
1. Go to any issue
2. Observe that the extension does nothing

**Expected behavior**
For the extension to work...

**Screenshots**

screenshot showing that the extension is present, but doesn't render anyhing

![screenshot of a github issue](https://github.com/gatewayapps/kamino/assets/895831/85cb1662-c159-496a-ad5c-730f91373d72)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 126.0.6478.127 (Official Build) (64-bit) 

**Additional context**

**Comment by johnmurphy01** [comment]
Thanks @patrickhlauke . I just got the email that my newest submission to update the extension was rejected for the same reason. I guess when that happened, the Chrome web store decided to also break the live version that is in production that was approved. Thanks Google...

I'll try to work on this today.

**Comment by johnmurphy01** [comment]
@patrickhlauke I've removed any references to CDNs and instead use the local files in the project. Hopefully this will resolve the issue. I've submitted another version for review

**Comment by patrickhlauke** [comment]
The odd thing is, the extension seems/seemed to work for some of my colleagues earlier. Not sure if there's some deeper problem/difference somewhere. But I'll keep my eye on when it updates for me, and see if that solves it.

**Comment by patrickhlauke** [comment]
@johnmurphy01 I'm a muppet. I realised just now what the actual problem was: yesterday I opted into GitHub's new "Beta" issue experience. That's what was causing the extension's buttons not to show up (I suspect the underlying structure for issue pages has changed, some `id` was changed, or similar, so the extension doesn't know where to render)

![screenshot of the 'Beta' - Try the new experience notification/button](https://github.com/gatewayapps/kamino/assets/895831/e50f3961-31ad-4426-96c2-64fc05150935)

**Comment by johnmurphy01** [comment]
That's okay. The newest version I submitted a few days ago was still rejected for the same reason outlined in this issue. So it needed to be fixed anyway.

**Comment by patrickhlauke** [comment]
Had a look at trying to make the extension also work/show up in the new (beta) experience https://github.com/gatewayapps/kamino/pull/218
