### ISSUE TITLE
[BUG] Issues can't be cloned if they have no description in the first comment.

### ISSUE THREAD

**Issue by MohammadLotfiA** [gatewayapps/kamino#224]
**Describe the bug**
Kamino does not clone an issue, if the issue is created without any description in a comment.

**To Reproduce**
1. Go to https://github.com/MoLoSec/MLA/issues/32
2. Clone the issue to a repo (without closing).
3. It won't clone it.

**Expected behavior**
I expect the issue to be cloned to my repo.
On the other hand, if the issue has a comment, it can clone it. For instance:
1) Go to: https://github.com/MoLoSec/MLA/issues/34
2) Clone the issue.
3) It will be cloned.

**Screenshots**
Issue without a comment (description) that CAN'T be cloned:
![image](https://github.com/user-attachments/assets/3ad75ff8-b6fa-4d8d-b822-8be63df0c5dc)

Issue with a comment (description) that can be cloned example 1:
![image](https://github.com/user-attachments/assets/9ba8d194-93b3-409a-ba87-5594f1c1c842)

Issue with a comment (description) that can be cloned example 2:
![image](https://github.com/user-attachments/assets/a1a966c9-64dc-490e-b475-b4a30fef0c2e)

Issue with a comment (description) that can be cloned example 3:
![image](https://github.com/user-attachments/assets/a647b504-0906-4be9-b52f-3b3726b163ee)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 131.0.2903.86 (Official build) (64-bit)

Also tested on:
 - OS: Windows 10
 - Browser: Chrome
 - Version 131.0.6778.109 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**
I don't exactly know why. As you can see in the screenshots, the first screenshot we can't see a description in the comment, and I can't clone that issue for some reason. But for the rest, since there is a description in the comment, I can clone them, and it's visible that I did clone them.
This is what I've found as a pattern. I've played with multiple stuff, token permission, different browser, timing (waiting for 20 minutes), enabling and disabling different options of Kamino, to no luck.
Maybe I'm missing something cause I'm beginner in this. So, apologies in advance.

By the way, I can't seem to see any batch clone button as well, if that option is still available.

**Comment by johnmurphy01** [comment]
@all-contributors please add @MohammadLotfiA for bugs

**Comment by johnmurphy01** [comment]
Thanks for the bug report @MohammadLotfiA! We will be working on a fix for this soon

**Comment by MohammadLotfiA** [comment]
Thanks a lot. 🚀

**Comment by johnmurphy01** [comment]
I submitted a new version to the chrome web store. `4.1.2` should be available in the coming days
