### ISSUE TITLE
[BUG] "Module is not defined"

### ISSUE THREAD

**Issue by kelson42** [gatewayapps/kamino#225]
**Describe the bug**
Using latest Kamino 4.1.1 with Chromium, the Kamino select box does not appear in the top of the right sidebar.
**To Reproduce**
1. Go to ['...'](https://github.com/kiwix/kiwix-build/issues/782)
2. Kamino selectbox is not visible like usual at the top of the right sidebar

**Expected behavior**
So far it has always work fine to me when I use it, but today the box is not there anymore and the console seems to show error in the extension.

**Screenshots**
![image](https://github.com/user-attachments/assets/466d9cba-4fc2-414c-b2f6-597d3a9a0d7e)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chromium
 - Version 4.1.1

**Comment by johnmurphy01** [comment]
@all-contributors please add @kelson42 for bugs

**Comment by johnmurphy01** [comment]
@kelson42 thanks for the bug report! We've determined that the issue is because Github changed their page layout. For private repos, the kamino button still appears but for public repos, it does not. We will be making a change that should support both flows.

**Comment by kelson42** [comment]
@johnmurphy01 Thank you very much, glad it has been worth to report the problem :)

**Comment by kelson42** [comment]
@johnmurphy01 Any new release if foreseen to make this fix live for end-users?

**Comment by johnmurphy01** [comment]
@kelson42 yes, I plan to get the release ready today or tomorrow and then it will go live after a review from Google. Look for version `4.1.2`

**Comment by johnmurphy01** [comment]
I submitted a new version to the chrome web store. `4.1.2` should be available in the coming days
