### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by danielgary** [gatewayapps/kamino#39]
v1.5 doesn't work, have the following issues:

Popup is in the top left corner.  Clicking ok doesn't work.  Booooo

**Comment by johnmurphy01** [comment]
Popup in the top left corner is expected. Clicking Yes not working is not expected. I'll look into it

**Comment by johnmurphy01** [comment]
The request to get the original issue did not populate the authorization token in the header. In addition, the variables that should have been populated with the data from the URL was being wiped out. This is fixed and will be in version 1.6

**Comment by RbAvci** [comment]
Kamino cloned this issue to [RbAvci/My-Coursework-Planner](https://github.com/RbAvci/My-Coursework-Planner/issues/67)
