### ISSUE TITLE
Dropdown control lists only a limited amount of repos to choose from.

### ISSUE THREAD

**Issue by mzia** [gatewayapps/kamino#75]
I'm seeing only about 90 some repos from my org. I have a lot more. Is there an limit to the drop down repo listing for the `clone to` button?

**Comment by johnmurphy01** [comment]
@mzia there is a limit but it should be around 1000 repos. I will do some digging and see if there's a problem with retrieving repos. Thanks for the feedback!

**Comment by johnmurphy01** [comment]
Github API only allows for 100 items per page. Will need to figure out a different way to gather user repos.

**Comment by johnmurphy01** [comment]
@mzia I've submitted a PR to to fix this issue. Once it's approved and merged, I'll create a new release for Kamino, version `2.2`

**Comment by johnmurphy01** [comment]
@mzia version `2.2` should be available to you shortly. If you notice anything else, feel free to create an issue.

**Comment by mzia** [comment]
Thanks a lot @johnmurphy01! It's working now :)

**Comment by johnmurphy01** [comment]
@mzia wonderful! I mentioned your username in the release notes on the Web Store as the person who identified the issue, hope that was okay.

**Comment by johnmurphy01** [comment]
@all-contributors please add @mzia for bug
