### ISSUE TITLE
"Package is invalid" error when installing from Chrome Web Store

### ISSUE THREAD

**Issue by demianmnave** [gatewayapps/kamino#98]
I'm getting the following error when installing V2.5 (August 15, 2017) from the Chrome Web Store:

```
Package is invalid. Details: 'Could not load javascript 'template.js' for content script.'.
```

I am running the latest 64-bit version of Chrome, 60.0.3112.101.

**Comment by johnmurphy01** [comment]
Thanks for reporting this! I'll look into it

**Comment by johnmurphy01** [comment]
@demianmnave this should be resolved with version `2.6`. I had forgotten to include a code file when publishing the extension. Thank you, thank you, thank you for catching this and reporting it!

**Comment by demianmnave** [comment]
@johnmurphy01 that worked, thanks for the quick response.  I'm having another problem, but I'll submit a new issue momentarily.

**Comment by johnmurphy01** [comment]
perfect! Thanks for the feedback

**Comment by johnmurphy01** [comment]
@all-contributors please add @demianmnave for bug
