### ISSUE TITLE
Repo drop-down and cloning operation become "stuck" after cloning two issues

### ISSUE THREAD

**Issue by demianmnave** [gatewayapps/kamino#99]
In short, I was able to clone two issues, but attempting to clone a third issue doesn't seem to work.  I don't know how to repro the problem, so I will just describe the behavior I'm seeing.

After cloning two issues:
1. From the issues list, click on an issue to open the issue page.  It doesn't seem to matter if the issue is open or closed.
2. Click the drop-down to show the list of accessible repos.  Since I've already cloned two issues, the target repo is listed first under "Last Used".
3. Select the target repo, and on the dialog that appears, click either "Clone" button to start the operation.

#### Results:
1. The dialog hides after clicking either "Clone" button.
2. The drop-down stays visible, even when clicking elsewhere on the page.
3. The issue is not cloned to the target repo.

#### Attempts to fix:
1. Restarted Chrome.
2. Removed and then re-added Kamino to Chrome, created a dedicated personal token for Kamino, and restarted.
3. Changed issue from "Closed" to "Open".

In case it matters, the source and destination repos are demianmnave/CML1 and demianmnave/CML, respectively.  If you need any more info, please let me know.

**Comment by johnmurphy01** [comment]
@demianmnave thanks. I will try to replicate

**Comment by johnmurphy01** [comment]
One thing you could try to help me out is open the Chrome developer tools. I'm sure you know how but in case not:
- Right click on the page and click `Inspect` or
- `Ctrl+Shift+I`

See if there are any errors in the console output when you're having the issue with Kamino

**Comment by johnmurphy01** [comment]
I was not able to reproduce by cloning 3 issues, one after the other. @demianmnave is there something different/special about the last issue you attempted to clone? Can you reproduce this _every_ time you attempt the test or doesn't it happen infrequently?

**Comment by demianmnave** [comment]
@johnmurphy01 the number of issues is probably unrelated.  You will be able to discern the differences between issues better than I, so here are the links:

#### Issues that were cloned successfully:
[CML1, issue 3](https://github.com/demianmnave/CML1/issues/3) -> [CML, issue 1](https://github.com/demianmnave/CML/issues/1)
[CML1, issue 4](https://github.com/demianmnave/CML1/issues/4) -> [CML, issue 2](https://github.com/demianmnave/CML/issues/2)

### Example of an issue that leads to a "stuck" operation:
[CML1, issue 5](https://github.com/demianmnave/CML1/issues/5)

Actually, the most obvious difference is that the failing issue is linked to a milestone, while the successful ones were not.  I'll remove the milestone and see if that changes the result.

I will also check for errors in the console.

**Comment by demianmnave** [comment]
Ah, removing the milestone did it; the target milestone doesn't exist in CML.  It's an easy fix, so maybe just a documentation update is needed to close out this issue.

**Comment by johnmurphy01** [comment]
thanks for the investigative work! What I can do is remove the milestone during the cloning process. That will prevent you, the user, from having to do anything(unless you want to have that milestone tied to the cloned issue in the new repo)

**Comment by demianmnave** [comment]
I added a new issue with a suggestion to support optionally migrating the milestone along with an issue.  As for this particular issue, I was able to move my issue list over to the new project, so feel free to close it.

Thanks for the help!

**Comment by johnmurphy01** [comment]
For the time being to address this issue, until #100 is settled, I'm going to ignore the migration of milestones when cloning.

**Comment by demianmnave** [comment]
Sounds like a plan, thanks again!

**Comment by johnmurphy01** [comment]
Version `2.7`
